ALTER TABLE "Usuario" ADD COLUMN "telefone" TEXT;

ALTER TABLE "Loja" ADD COLUMN "email" TEXT;
ALTER TABLE "Loja" ADD COLUMN "telefone" TEXT;
ALTER TABLE "Loja" ADD COLUMN "documento" TEXT;
ALTER TABLE "Loja" ADD COLUMN "endereco" TEXT;
ALTER TABLE "Loja" ADD COLUMN "bairro" TEXT;
ALTER TABLE "Loja" ADD COLUMN "cidade" TEXT;
ALTER TABLE "Loja" ADD COLUMN "estado" TEXT;
ALTER TABLE "Loja" ADD COLUMN "cep" TEXT;
